version: '2'
services:
    hackboard-app:
        image: hackboard
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hackboard-mysql:3306/hackboard?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hackboard-mysql:
        extends:
            file: mysql.yml
            service: hackboard-mysql
